version: 0.2
phases:
  build:
    command:
      - echo Entered the build phase
      - mvn clean package
  post_build:
    command:
      - echo build completed successfully
artifacts:
  files:
    - target/course-service.jar
  discard-path: yes